cloudnative-pg:
  podLabels:
    app: edb-cnp-gke-autopilot
  serviceAccount:
    create: false
  rbac:
    create: false
  webhook:
    livenessProbe:
      initialDelaySeconds: 30
    readinessProbe:
      initialDelaySeconds: 30
metering:
  image:
    image: "metering_image_repo:latest"
    pullPolicy: IfNotPresent
  reporting:
    metricName: "count"
    scheme: "http"
    host: "localhost"
    port: "4567"
    path: "/report"
    status: "/status"
    interval: "1m"
  stateConfigMapName: "metering-state"
  ubbImage:
    image: "gcr.io/cloud-marketplace-tools/metering/ubbagent:latest"
    pullPolicy: IfNotPresent
  reportingSecret: ""
  labels:
    app: edb-cnp-gke-autopilot-metering
  secretName: ""
  serviceAccountName: ""
  podSecurityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
  http:
    readinessProbe:
      initialDelaySeconds: 15
    livenessProbe:
      initialDelaySeconds: 15
  service:
    type: ClusterIP
    port: 443
  resources: { }
    # If you want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #
    # limits:
    #   cpu: 100m
    #   memory: 200Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 10001
    runAsGroup: 10001
    capabilities:
      drop:
        - "ALL"
